name: AuthSocial
version: '0.5.0'
main: io.github.kosyakmakc.socialBridge.AuthModule.paper.AuthModulePlugin
api-version: '1.21'
authors: [ kosyakmakc ]
depend: [SocialBridge, SocialBridge-telegram]
folia-supported: true
