name: AuthSocial
version: '0.4.1'
main: io.github.kosyakmakc.socialBridge.AuthModule.paper.AuthModulePlugin
api-version: '1.21'
authors: [ kosyakmakc ]
depend: [SocialBridge-paper, SocialBridge-telegram-paper]
folia-supported: true